### ISSUE TITLE
Feature request: leading icons for filename-typed titles, and 2 bugs found

### ISSUE THREAD

**Issue by lethefrost** [stargrey/obsidian-better-codeblock#6]
@lethefrost 
I'm a little confused about what you mean. Under what circumstances will there be a form like `filename.extension`? Could you describe it in detail?

This was actually a mistake on my part, but I didn't fix it because I thought these left blank spaces would indicate a collapsed section below the code block.

If you don't like it, you can put this code in `style.css` or your CSS snippets to close this effect
```
pre[class*=language-].code-block-pre__has-linenum {
  padding-bottom: 0px;
}
```

_Originally posted by @stargrey in https://github.com/stargrey/obsidian-better-codeblock/issues/4#issuecomment-1144895080_

Hi, Thank you for giving this css selector!

I am sorry that I might have not explained it clearly and caused you confusion. I made a screenshot to better describe a use case.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/47198693/172032094-0c132efc-69c3-4874-b32a-8051d7e66e14.png">

By the way, I just found **two more bugs**:

1. Any title we add after the language indicator `language:title` will disable the code block language syntax highlighting in preview mode. 
    - In live preview editor mode, the syntax highlighting is not affected by a `:title` following the language indicator (As in the attached screenshot below, in editor mode, the two kinds of title are both highlighted) <img width="694" alt="image" src="https://user-images.githubusercontent.com/47198693/172032292-559154ee-a0ab-4131-815c-d8f3cf5aff7a.png"> <img width="692" alt="image" src="https://user-images.githubusercontent.com/47198693/172032303-97dd9950-975c-4747-9716-ce775f303c56.png">
    - However, when we switch to preview mode, it is broken by having a title. <img width="707" alt="image" src="https://user-images.githubusercontent.com/47198693/172032347-3229bc22-c223-468c-a6dd-3aa8e1d0f57d.png"> <img width="705" alt="image" src="https://user-images.githubusercontent.com/47198693/172032349-6891aaf8-1578-4903-8b99-9838fd6d866f.png">
2. If a line in the code block is very long to occupy the full width and triggers line wrap, the line number feature has a bug of alignment. Please see below. <img width="291" alt="image" src="https://user-images.githubusercontent.com/47198693/172032457-a8d095fc-1a0e-46de-9dae-b32b4b412b3e.png">

**Comment by stargrey** [comment]
That's a good idea, and I'll try to do it, but the icon might be a little hard to find.
The first bug was fixed in 1.0.5.
The second bug I have no idea for the moment, but you can use some themes that do not automatically line feed, like Blue Topaz.

**Comment by lethefrost** [comment]
> That's a good idea, and I'll try to do it, but the icon might be a little hard to find. The first bug was fixed in 1.0.5. The second bug I have no idea for the moment, but you can use some themes that do not automatically line feed, like Blue Topaz.

Hi @stargrey , I found that the first bug is not fixed (I have v1.0.6 installed). Instead of bringing the syntax highlighting back in a titled code block, it turns to use the whole line as the language name, without parsing or extracting the `:title` section which should be shown in the top left corner.

**Comment by stargrey** [comment]
@lethefrost 
> Hi @stargrey , I found that the first bug is not fixed (I have v1.0.6 installed). Instead of bringing the syntax highlighting back in a titled code block, it turns to use the whole line as the language name, without parsing or extracting the `:title` section which should be shown in the top left corner.

To solve this problem, I modified the syntax used by the plugin. Check out `readme.md` and use the new syntax to add title, in addition to that, you can now add highlighted lines.

**Comment by lethefrost** [comment]
> @lethefrost
> 
> > Hi @stargrey , I found that the first bug is not fixed (I have v1.0.6 installed). Instead of bringing the syntax highlighting back in a titled code block, it turns to use the whole line as the language name, without parsing or extracting the `:title` section which should be shown in the top left corner.
> 
> To solve this problem, I modified the syntax used by the plugin. Check out `readme.md` and use the new syntax to add title, in addition to that, you can now add highlighted lines.

Hi, thank you for the explanation. Sorry for the late reply. It's very cool to have a new feature to highlight some lines of the code block!! I definitely love it. Thanks for the update!
